setup.py

Currently installing `arxiv.py` in a brand new virtualenv will yield an `ImportError` on import because `requests` is not declared as a dependency:
```
In [1]: import arxiv
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1688b216db7c> in <module>()
----> 1 import arxiv
/Users/jacquerie/arxiv.py/arxiv/__init__.py in <module>()
----> 1 from .arxiv import *
/Users/jacquerie/arxiv.py/arxiv/arxiv.py in <module>()
3
4 import feedparser
----> 5 from requests.exceptions import HTTPError
6
7
ImportError: No module named requests.exceptions
```
This PR adds `requests` to the `install_requires` so that this won't happen anymore.

Add requests to dependencies

---

arxiv/arxiv.py

like `query('é')`
Also add support for a result without a status
because `query` would error on "result['status']" with a `KeyError`

Add support for unicode queries

---

arxiv/arxiv.py

If I want to make sure that I get information about a specific paper, of which I know the identifier, it is better to query the ID directly.
The change leaves the functionality unchanged with the default `id=False`.

Add kwarg to query specifically for IDs instead of a general arXiv query

---

arxiv/arxiv.py

Previous functionality is unchanged with defaults `prepend_id=False, slug=False`.
- `prepend_id` adds the arXiv ID with version to the pdf filename.
- `slug` removes all non-alphanumeric characters and replaces them with underscores. Duplicate underscores are also removed.

Extend filename functionality

---

README.md
arxiv/arxiv.py
tests/test_download.py

Modified "download" so it can download source .tar.gz file
To download source, the keyword argument "source" must be passed with 
True value. Otherwise it downloads the .pdf.
[download preprint source files #36](https://github.com/lukasschwab/arxiv.py/issues/36)

Modified "download" so it can download source .tar.gz file

---

README.md
arxiv/arxiv.py
docs/index.html
tests/test_result.py

+ Finds the pdf_url during Result construction and stores it as `Result.pdf_url`.
+ Deprecates the `get_pdf_url` accessor.
It's unfortunate that we're duplicating data on the Result object again, but it makes sense to move towards a more structured version of links (e.g. indexing links in a dict by their content type) rather than keeping a list.
I'm also pretty confident that PDF URL access constitutes the vast majority of `Result.links` usage, since the `Result.entry_id` is a fine URL for the article metadata. Exposing `pdf_url` is better than having users modify `entry_id`s into homegrown PDF URLs.
None: `get_pdf_url` remains implemented.
**Note:** it may make sense to remove `get_pdf_url` whenever …

Store `Result.pdf_url` member variable

---

arxiv/arxiv.py
docs/index.html

Should improve readability in interactive usage.
Adds standard Python [`__str__` and `__repr__` methods](https://stackoverflow.com/a/2626364/6226586) to all declared classes besides the enums.
+ Remove feedparser structs from constructors: these are technically exposed, even for subclasses.
+ Changes `Result.Author.__init__` to take members instead of a `FeedParserDict`.
+ Changes `Result.Link.__init__` to take members instead of a `FeedParserDict`.
+ Breaks any code that depends on the existing (Python-default) `__str__` and `__repr__` behavior.
EPS-Libraries-Berkeley/volt#161: this came up as a pain point when migrating their …

Add `__str__` and `__repr__` methods to all non-Enums

---

arxiv/arxiv.py
docs/index.html
tests/test_result.py

This conversion was irritating in my work with the volt tutorial tonight. This change is major enough to warrant a v1.1.0 release: it changes the type (beyond correcting the annotation) of a field.
The package could keep the old field around and namespace access to the new one, but I don't think v1.x.x adoption is widespread enough to merit the technical debt.
+ Changes the type of `Result.updated`: `time.struct_time` → `datetime`.
+ Changes the type of `Result.published`: `time.struct_time` → `datetime`.
+ Fix https://github.com/lukasschwab/arxiv.py/issues/57; this uses the stdlib option described in that thread.
+ …

Convert `time.struct_time` fields to datetimes

---

arxiv/arxiv.py
docs/index.html
tests/test_result.py

**Note:** this repo's releases have been frequent enough that I'll let this PR sit until Friday/Saturday.
+ Updates `__repr__` implementations to format constructor arguments using `repr(...)`. Before this change, quotes were missing from what *should* have been string literals in the `__repr__` return values: `arxiv.Result.Author(Some Name)` should be `arxiv.Result.Author("Some Name")`.
+ Adds `__eq__` helpers for checking equality; relies naively on `(Result).entry_id`, `(Result.Author).name`, and `(Result.Link).href`.
Minor breaking changes. I'm tempted to call this release 1.1.1, but changing equality behavior probably merits 1.2.0.
+ Changes equality checks: behavior before this change is to compare object addresses. …

Improve Result and subclass methods for Python builtins

---

arxiv/arxiv.py
docs/index.html

Includes the first entry summary for a non-bozo feed returned with a non-200 status. For example, extracts `incorrect id format for 0112019v1` from
```xml
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
<link href="http://arxiv.org/api/query?search_query%3D%26id_list%3D0112019v1%26start%3D0%26max_results%3D10%26sortBy%3Drelevance%26sortOrder%3Ddescending" rel="self" type="application/atom+xml"/>
<title type="html">ArXiv Query: search_query=&amp;id_list=0112019v1&amp;start=0&amp;max_results=10&amp;sortBy=relevance&amp;sortOrder=descending</title>
<id>http://arxiv.org/api/ICCqNwWyrQkMAErZidA/EoTr7/o</id>
<updated>2021-07-12T00:00:00-04:00</updated>
<opensearch:totalResults xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/">1</opensearch:totalResults> …
```

Include summary from feed entry in HTTPErrors

---

arxiv/arxiv.py
docs/index.html
setup.py
tests/test_result.py

+ Adds a unit test reproducing #74.
+ Modifies `(Result).get_short_id()` to return fully-qualified pre-March 2007 IDs (including the archive) rather than just its numeric component.
`(Result).get_short_id()` return values change. Users keying on short IDs (e.g. to see if they have already processed an article) may re-process articles because of this value change.
Of course, keying on short IDs was broken: legacy short IDs were not truly unique.
Fix #74

Return fully-qualified pre-March 2007 IDs from `get_short_id`

---

arxiv/arxiv.py
docs/index.html
tests/test_client.py

Sleeps between API request tries.
+ Breaks a recursive helper––which handles the rate limiting and represents a single request "try"––out of `_parse_feed`.
+ Adds a test for this behavior.
None: even the `_parse_feed` interface is unchanged.
Resolves the in-code `NOTE` above `_parse_feed`:
```
```
Follows up on PhosphorylatedRabbits/paperscraper#10; merits a version bump there.

Run retries recursively to sleep between erroneous responses

---

arxiv/arxiv.py
docs/index.html
setup.py
tests/test_client.py

+ When an entry in an arXiv API feed is missing its ID (a *very* required field),
1. Throw an error (`_from_feed_entry`)
2. Catch that error in the generator, warn, and proceed to the next entry without yielding
+ Adds a test with known-buggy queries.
+ Increments version for a patch release.
Considered some drawbacks to this new behavior, but breaking the ordinal relationship seems better than introducing a new zero- or invalid-state (like the `bozo` flag in `feedparser`): https://github.com/lukasschwab/arxiv.py/issues/80#issuecomment-899164524
None; elides an unexpected and unhandled error.
Fix #80.

Skip invalid entries from nonexistent `id_list` IDs

---

.github/workflows/python-package.yml
Makefile
requirements.txt

Strictly updates the developer workflow.
+ Adds a dev dependency: [trailofbits/pip-audit](https://github.com/trailofbits/pip-audit).
+ Adds a Make target for running `pip-audit` against requirements.txt: `make audit`.
+ Adds `make audit` to the python-package.yaml GitHub workflow.
No changes to package behavior.
N/A

Use `pip-audit` to audit dependencies before merging PRs

---

arxiv/arxiv.py
docs/index.html

Updates documentation to warn users off pre-encoding query strings.
Unless I hear otherwise, I don't think this merits a patch; updating the hosted documentation is likely enough.
None.
+ Fix #90

Add docstring warning about expected `(Search).query` encoding

---

.github/workflows/docs.yml
Makefile
docs/index.html
requirements.txt

Does what it says on the tin.
+ Bumps a dev dependency.
+ Rebuilds documentation.
+ Tweaks a build target: the search.json artifact is now search.js.
None.
Unblock https://github.com/lukasschwab/arxiv.py/pull/94

Bump pdoc version to 12.1.0

---

.github/workflows/docs.yml
.github/workflows/python-package.yml
docs/index.html
requirements.txt

Does what it says on the tin.
From annotations on a recent run:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
+ None.
e.g. https://github.com/lukasschwab/arxiv.py/actions/runs/4059309134

Upgrade actions/checkout@v2 to actions/checkout@v3

---

arxiv/arxiv.py

In case a longer query fails you can receive an error looking like e.g.  arxiv.arxiv.UnexpectedEmptyPageError: Page of results was unexpectedly empty (http://export.arxiv.org/api/query?search_query=cat%3Acs.CV&id_list=&sortBy=submittedDate&sortOrder=descending&start=2000&max_results=100)
The offset would be 2000  in that example. To prevent to start the same query beginning from zero again, you could provide offset as an argument to restart the query from the point onwards.

Making offset configurable for Client.results(...)

---

setup.py

Concession to get the Shields.io badge to work. `python_requires` doesn't cut it: https://github.com/badges/shields/issues/5550. I released #111 as 1.4.6 too hastily.
[Piggyback on GitHub search results.](https://github.com/certbot/certbot/blob/399b932a869403b142fb0271aec510614085d6ed/acme/setup.py#L38)
None.
None.

Indicate Python version in trove classifiers

---

Makefile
README.md

+ Use `--no-search` to skip generating the search artifacts. Eliminates the cleanup step, skips an unnecessary build stage.
+ Eliminate badges in pdoc navigation by moving them in the README. I like the inline look on GitHub, but it's not worth version-controlling a custom template with tweaked CSS.[^css]
[^css]: Custom CSS would look like this:
```css
nav.pdoc img {
display: none;
}
```
None.
None.

Simplify `pdoc` build, eliminate nav badges

---

arxiv/arxiv.py
setup.py
tests/test_download.py

Replace `/` with `_` in download ID components
Fixes #117. Differentiates character-escaping strategies for paper titles and paper IDs:
+ IDs: only replace `/` with `_`, to account for legacy-form IDs.
+ Titles: replace non-word (i.e. `[^\w]`) characters with `_`.
Adds a regression test.
I'm not super happy with this solution, but I think it's minimally-breaking. Have to retain backwards-compatibility with a bad filename-sanitization scheme — too bad!
For more sophisticated (but more restricted) strategies, see e.g. Django's `slugify`.
None
+ Fix #117

Replace `/` with `_` in legacy-format IDs in download filenames

---

arxiv/arxiv.py

After investigating why I never get search results using arxiv.py, I eventually found out that the ArXiv http endpoint (without SSL) simply does not return any data. I am unsure whether this is a recent change in the ArXiv API or a issue specific to my computer (I am running Pop_OS!). 
However, changing the API Endpoint from http to https seems to be a fairly simple and effective solution. 
> None
> None

Use HTTPS in API Endpoint

---

README.md
arxiv/arxiv.py
setup.py
tests/test_client.py
tests/test_result.py

Route requests via HTTPS rather than HTTP.
Per #129, both seem flaky but HTTPS seems generally more stable. Observed:
+ #128 
+ https://github.com/lukasschwab/arxiv.py/pull/127#issuecomment-1763222100
None.
Extends #128.

Standardize on HTTPS over HTTP

---

arxiv/arxiv.py
setup.cfg
tests/test_result.py

+ Temporarily increases log noise from tests while working on #129.
+ Adds request URLs to log messages for ease of access.
None
+ Closes #130.

Improve logging: standard formatting, verbose tests

---

.github/workflows/python-package.yml

Does what it says on the tin. Clears node deprecation warnings.
None; only changes CI execution.
N/A

Use `setup-python@v4`, cache pip dependencies

---

requirements.txt
setup.py

Does what it says on the tin; guard against breaking changes [staged](https://github.com/kurtmckee/feedparser/blob/889d04565fe01384a49b63db7cf0fccacea197a4/changelog.d/20230403_214917_kurtmckee_rm_custom_http_client_code.rst#breaking-changes) for (presumably) a feedparser 7 release.
Once `feedparser` isn't handling HTTP errors, it should be easier to upgrade; at that point, error handling _downstream_ of `feedparser` can focus on _parse_ errors exclusively.
None.
- #129 disucssion of the `User-Agent` header reveals a future release of `feedparser` will eliminate the `agent` named parameter to `parse`.

Pin `feedparser==6.0.6`

---

.github/workflows/python-package.yml
arxiv/arxiv.py
requirements.txt
setup.cfg
setup.py
tests/test_client.py
tests/test_result.py

+ Separates HTTP request from `feedparser.parse` call.
+ Sets a package-specific default `User-Agent` header.
Breaking change; probably necessitates a 2.0.0 release.
+ **Breaks exception types.**
+ Breaks internal `_parse_feed` and `__try_parse_feed` function signatures.
Part of stability initiatives per #129.

Separate HTTP request from `feedparser.parse`

---

README.md
arxiv/arxiv.py
tests/test_api_bugs.py
tests/test_client.py

+ Make `Search.max_results` an `int | None`.
+ Make `Client.delay_seconds` a `float`.
+ Update tests accordingly.
Major refactor of `Client.results`. It's a matter of taste, but the code is much simpler: use `itertools` to enforce `max_results` rather than varying page size.
None. Search constructor retains backwards compatibility for `float('inf')`; other floats were effectively unsupported (broken).
- Fix #123
- Obviate #124

Improve `max_results`/`delay_seconds` types, defaults

---

README.md
arxiv/arxiv.py
tests/test_result.py

+ Deprecates `Client.results`; encourage `Client` reuse.
+ Consistent rate-limiting.
+ Session reuse.
+ Minimize the documented API surface.
+ Deletes the already-deprecated `Search.get`/`Client.get` methods; `results` is a drop-in replacement.
None.

Eliminate `get`, deprecate `Search.Results`

---

.github/workflows/python-package.yml
README.md
arxiv/arxiv.py
setup.py
tests/test_api_bugs.py
tests/test_client.py
tests/test_result.py

Temporary recipient branch for changes that'll go into the 2.0.0 release.
+ Largely a reaction to #129.
+ #137
+ #138 
+ #140 

Bump version to 2.0.0

---

README.md

Does what it says on the tin. README.md should really be restructured to prioritize _examples_ and _prominent links to the generated documentation_ — class members are better-documented inline and in the generated docs.
None, docs only.
+ Fix #122

Add an unencoded query example to README.md

---

README.md
arxiv/__init__.py
arxiv/arxiv.py

Try to improve time-to-first-query.
+ Add badge link to the full package documentation
+ Pull examples to top of file
+ Simplify type documentation to conceptual overviews
+ Restructure references to members so pdoc renders them as links
None; only documentation.
None.

Restructure README.md: focus on generated docs

---

README.md

Tin.
None.
- Belonged in #144.

Typo: use 'a' rather than 'an' before DEBUG

---

arxiv/__init__.py
arxiv/arxiv.py
setup.py

Does what it says on the tin.
None.
To be rolled up in release notes.

Bump version to 2.1.0

---

tests/test_client.py

Theory: simple fly.io-hosted service might be more universally available, and easier for me to run locally. I observed some httpstat.us downtime.
None; only tests.
+ CI failures on #147.

Use teapot.fly.dev over httpstat.us in tests

---

.github/workflows/static-analysis.yaml
Makefile
arxiv/__init__.py
requirements.txt
ruff.toml
tests/test_client.py
tests/test_download.py
tests/test_package.py
tests/test_result.py

Consolidates on `ruff` for both formatting and linting.
+ Bumps `ruff` version.
+ Updates the `make format` target.
+ Reformats.
May need to additionally update the `black` check in GitHub Action.
None; just style.
None.

Format with `ruff`

---

tests/test_client.py

+ Eliminates dependency on teapot.fly.dev; see #148.
+ Fixes #149. Improve test speed, robustness.
In the future we should store some and mock some arXiv API responses. At the very least, this offers some backup for when the API is down; of course, it introduces the risk of divergence from the live API.
None: only changes tests.
+ Fix #149

Mock `requests.Session.get` in `TestClient`

---

requirements.txt

Does what it says on the tin for the two `==`-pinned non-development dependencies, `requests` and `feedparser`.
Deserves some thought on risk: what if one of these dependencies incorrectly labels breaking changes in a patch version?
None.
Closes #161.
- [-] (If appropriate) `README.md` example usage has been updated.

Loosen version requirements to compatibility operator `~=`

---

setup.py

You merged PR #162 updating constraints in `requirements.txt` but unfortunately forgot to update the `install_requires` field in `setup.py`. So right now both the release in PyPI and the local install from Git still suffer from the problem described in #161. 
Thus, this PR is a logical continuation to #162 and aims to update `setup.py`.
None
Completes the fix of #161 
- [-] (If appropriate) `README.md` example usage has been updated.

Loosen requirements in `setup.py`

---

arxiv/__init__.py
setup.py
tests/test_client.py

+ Use `Optional` type hints where appropriate.
+ Retains the 'if present' docstring language: this appears in [arXiv's API documentation](https://info.arxiv.org/help/api/user-manual.html#3322-summary-author-and-category).
+ There may be more fields that deserve this annotation; deciding to handle those in follow-up diffs.
+ Belatedly `make format`.
None — only changes type _hints._ `Optional[T]` is an alias for `T | None`, which describes the existing data.
+ Fix #163

Use `Optional` type hints where appropriate

---

.github/workflows/python-package.yml
.github/workflows/static-analysis.yaml
arxiv/__init__.py
arxiv/arxiv.py
setup.py
tests/test_api_bugs.py
tests/test_package.py

- no issues
- no breaking changes
I noticed that the download URL used in the code is the one provided by the API, for example:
```xml
<link title="pdf" href="http://arxiv.org/pdf/2307.10160v1" rel="related" type="application/pdf"/>
```
On [their API documentation site](https://info.arxiv.org/help/bulk_data.html#play-nice) they explicitly state that:
> We ask that users intent on harvesting use the dedicated site export.arxiv.org for these purposes, which contains an up-to-date copy of the corpus and is specifically set aside for programmatic access.
This pull request replaces that part of the URL dynamically for downloading and should thereby oblige by their request.
.. I found this because I ran into weird issues when bulk downloading, like throtteling or empty pages. Once I adjusted …

Adjust download URL to utilize their dedicated site for harvesting
